### ISSUE TITLE
Getting errors when testing the app

### ISSUE THREAD

**Issue by maheraldous** [m-muhsin/woosesh-store#3]
I am getting the following errors when I am testing the app
https://prnt.sc/o1lu2d
https://prnt.sc/o1lu5l
https://prnt.sc/o1lu9b
https://prnt.sc/o1lvbt
I just wanted to test the app before starting going through it but the app didn't work at all.
I want to fix the errors but I don't know how because I am new in React Native.
Below are the codes in package.json and app.json without any change

The package
`{
  "name": "my-new-project",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^30.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-htmlview": "^0.13.0",
    "react-navigation": "^2.16.0"
  },
  "devDependencies": {
    "jest-expo": "30.0.0"
  }
}`

The app
`{
  "expo": {
    "name": "woosesh-store",
    "description": "A very interesting project.",
    "slug": "woosesh-store",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}`

**Comment by maheraldous** [comment]
Update I am getting only this error when I use SDK 33.0.0 instead of 30.0.0 in your project https://prnt.sc/o1xj7m I check out the packges that displays in the errors and all of them are exists.

**Comment by m-muhsin** [comment]
Hi Maher,
Sorry for getting back late on this. 

I guess you can work with v30 for the time being. I may get back to working on this app in the future, no plans for it as of now.

**Comment by maheraldous** [comment]
Thank you and I will be happy if you just make a video how to setup every thing in the end beacuse a video is better than documentation sometimes. :)

**Comment by m-muhsin** [comment]
I did a whole talk on this same thing. You could access it if you sign up for WP Sessions.
Here is my session: https://wpsessions.com/session/creating-a-woocommerce-mobile-app-with-react-native/

**Comment by maheraldous** [comment]
I think on youtube it will be better for all. Anyway I am developing my own store app right now. So when I am finish I will make it publicly so that if someone can make it more powerful it will be useful for people who needs it. I used your app as references and it's really good :)

**Comment by m-muhsin** [comment]
Not sure if the WooSesh organizers would allow it to be posted on YouTube. Thanks for your kind words! Also, wish you the best with your endeavors!
