### ISSUE TITLE
are you finished this app 

### ISSUE THREAD

**Issue by ahmedemad2345** [m-muhsin/woosesh-store#4]
hello, i run this app and it's like very good so if you have finished it please send me the full source code or if you didn't finished it yet tell me how to finish it by self or what's the course should i learn to make a woocommerce rest api app from zero to hero thank you anyway :)

**Comment by m-muhsin** [comment]
Hi Ahmed,
I probably won't continue with it for the time being.

I can't think of a course to finish this exact app, but this course is pretty good:
https://www.udemy.com/the-complete-react-native-and-redux-course/

**Comment by ahmedemad2345** [comment]
OK bro thank you so much and if you continue working in this project please send me an email to ahmedemad2345@yahoo.com and till you do it i will learn react native
